In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("imdb_top_1000.csv")

In [3]:
df["Released_Year"]=df["Released_Year"].str.replace(")","0")

In [4]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000"

In [5]:
df['Released_Year'].unique()

<ArrowStringArray>
['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010', '1999',
 '2001', '1966', '2002', '1990', '1980', '1975', '2020', '2019', '2014',
 '1998', '1997', '1995', '1991', '1977', '1962', '1954', '1946', '2011',
 '2006', '2000', '1988', '1985', '1968', '1960', '1942', '1936', '1931',
 '2018', '2017', '2016', '2012', '2009', '2007', '1984', '1981', '1979',
 '1971', '1963', '1964', '1950', '1940', '2013', '2005', '2004', '1992',
 '1987', '1986', '1983', '1976', '1973', '1965', '1959', '1958', '1952',
 '1948', '1944', '1941', '1927', '1921', '2015', '1996', '1989', '1978',
 '1961', '1955', '1953', '1925', '1924', '1982', '1967', '1951', '1949',
 '1939', '1937', '1934', '1928', '1926', '1920', '1970', '1969', '1956',
 '1947', '1945', '1930', '1938', '1935', '1933', '1932', '1922', '1943',
   'PG']
Length: 100, dtype: str

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   Genre          1000 non-null   str
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   str
 10  Star1          1000 non-null   str
 11  Star2          1000 non-null   str
 12  Star3          1000 non-null   str
 13  Star4          1000 non-null   str
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    str
dtypes: float64(2), int64(1), str(13)
memory usage: 520.7 KB

In [7]:
gross_sum=df.groupby("Certificate")["Gross"].sum()
print(gross_sum)

Certificate
16
A           2,83,41,46913,49,66,4115,73,00,00010,79,28,762...
Approved    39,69,8934,49,19143,60,00043,60,0002,36,50,000...
G           1,63,24519,18188,19,0281,77,34521,89,67,6208,0...
GP                                            39,48113,78,435
PG          9,33,93312,29,1978,57,52426,03,0614,49,08,0002...
PG-13       70,98,49214,98,2102,35,30,89244,45,75659,90,07...
Passed      2,88,47557,20,00028,87754,50,00010,17750,14,00...
R           21,65,40,9093,25,72,57767,19,8648,34,71,5117,8...
TV-14
TV-MA
TV-PG                                                1,06,662
U           43,60,00037,78,45,90531,55,44,7501,00,55,8595,...
U/A                                               2,60,20,957
UA          53,48,58,44429,25,76,19533,02,52,18234,25,51,3...
Unrated                                              3,00,000
Name: Gross, dtype: str

In [8]:
gross_sum2=df.groupby("Certificate")["Gross"].agg(["min","max"])
print(gross_sum2)

                     min          max
Certificate
16                   NaN          NaN
A            1,12,86,112    96,00,000
Approved     2,36,50,000    49,05,000
G               1,63,245    88,19,028
GP             13,78,435       39,481
PG           1,17,98,616    94,50,000
PG-13        1,03,01,706    94,22,422
Passed       1,00,00,000    96,00,000
R            1,00,95,170    94,39,923
TV-14                NaN          NaN
TV-MA                NaN          NaN
TV-PG           1,06,662     1,06,662
U            1,00,19,307    99,29,135
U/A          2,60,20,957  2,60,20,957
UA           1,06,00,000     9,85,912
Unrated         3,00,000     3,00,000

In [9]:
df["Gross"]=df["Gross"].str.replace(",","")

In [10]:
df["Gross"].isna().sum()

np.int64(169)

In [11]:
df["Gross"]=df["Gross"].fillna(0)

In [12]:
df["Gross"]=df["Gross"].astype('int')

In [13]:
df["Gross"].isna().sum

<bound method Series.sum of 0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Gross, Length: 1000, dtype: bool>

In [14]:
df.groupby('Certificate')["Gross"].agg(["min", "max"])

                  min        max
Certificate
16                  0          0
A                   0  335451311
Approved            0   23650000
G                   0  218967620
GP              39481    1378435
PG                  0  102308889
PG-13               0  209028679
Passed              0   30500000
R                   0  363070709
TV-14               0          0
TV-MA               0          0
TV-PG               0     106662
U                   0  936662225
U/A          26020957   26020957
UA                  0  858373000
Unrated        300000     300000

In [15]:
df.sort_values(["Released_Year"])

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
321,https://m.media-amazon.com/images/M/MV5BNWJiNG...,Das Cabinet des Dr. Caligari,1920,NaN,76 min,"Fantasy, Horror, Mystery",8.1,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",NaN,Robert Wiene,Werner Krauss,Conrad Veidt,Friedrich Feher,Lil Dagover,57428,0
127,https://m.media-amazon.com/images/M/MV5BZjhhMT...,The Kid,1921,Passed,68 min,"Comedy, Drama, Family",8.3,"The Tramp cares for an abandoned child, but ev...",NaN,Charles Chaplin,Charles Chaplin,Edna Purviance,Jackie Coogan,Carl Miller,113314,5450000
568,https://m.media-amazon.com/images/M/MV5BMTAxYj...,Nosferatu,1922,NaN,94 min,"Fantasy, Horror",7.9,Vampire Count Orlok expresses interest in a ne...,NaN,F.W. Murnau,Max Schreck,Alexander Granach,Gustav von Wangenheim,Greta Schröder,88794,0
194,https://m.media-amazon.com/images/M/MV5BZWFhOG...,Sherlock Jr.,1924,Passed,45 min,"Action, Comedy, Romance",8.2,"A film projectionist longs to be a detective, ...",NaN,Buster Keaton,Buster Keaton,Kathryn McGuire,Joe Keaton,Erwin Connelly,41985,977375
193,https://m.media-amazon.com/images/M/MV5BZjEyOT...,The Gold Rush,1925,Passed,95 min,"Adventure, Comedy, Drama",8.2,A prospector goes to the Klondike in search of...,NaN,Charles Chaplin,Charles Chaplin,Mack Swain,Tom Murray,Henry Bergman,101053,5450000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,https://m.media-amazon.com/images/M/MV5BZGE1MD...,Soul,2020,U,100 min,"Animation, Adventure, Comedy",8.1,"After landing the gig of a lifetime, a New Yor...",83.0,Pete Docter,Kemp Powers,Jamie Foxx,Tina Fey,Graham Norton,159171,0
464,https://m.media-amazon.com/images/M/MV5BNmI0MT...,Dil Bechara,2020,UA,101 min,"Comedy, Drama, Romance",7.9,The emotional journey of two hopelessly in lov...,NaN,Mukesh Chhabra,Sushant Singh Rajput,Sanjana Sanghi,Sahil Vaid,Saswata Chatterjee,111478,0
612,https://m.media-amazon.com/images/M/MV5BYjYzOG...,The Trial of the Chicago 7,2020,R,129 min,"Drama, History, Thriller",7.8,The story of 7 people on trial stemming from v...,77.0,Aaron Sorkin,Eddie Redmayne,Alex Sharp,Sacha Baron Cohen,Jeremy Strong,89896,0
613,https://m.media-amazon.com/images/M/MV5BOTNjM2...,Druk,2020,NaN,117 min,"Comedy, Drama",7.8,"Four friends, all high school teachers, test a...",81.0,Thomas Vinterberg,Mads Mikkelsen,Thomas Bo Larsen,Magnus Millang,Lars Ranthe,33931,0
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,173837933

In [16]:
df["Released_Year"].dtype

In [17]:
df['Released_Year'] = df['Released_Year'].astype(int)

ValueError: invalid literal for int() with base 10: 'PG'

In [ ]:
df_direc_time=

In [ ]:
df_direc_time["active"]=df_direc_time['max']-df_direc_time['min']
df_direc_time.sort_values(by='active',ascending=False).head()

NameError: name 'df_direc_time' is not defined

In [ ]:
df_direc_time=df.groupby("Director")["Released_Year"].agg(["mean", "max"])

TypeError: dtype 'str' does not support operation 'mean'

In [ ]:
df_dir_bud["Gross"]=df_dir_bud['Gross']/1000000
df_dir_bud["Gross"]

NameError: name 'df_dir_bud' is not defined